import React from 'react';
import { Printer, X, Bell, CheckCircle2, Clock, MapPin, Phone } from 'lucide-react';
import type { Order, CafeInfo } from '../../types.js';

interface KitchenOrderTicketProps {
  order: Order;
  cafeInfo?: CafeInfo | null;
  onClose?: () => void;
  isAutoGenerated?: boolean;
}

export const KitchenOrderTicket: React.FC<KitchenOrderTicketProps> = ({
  order,
  cafeInfo,
  onClose,
  isAutoGenerated = false,
}) => {
  const handlePrint = () => {
    window.print();
  };

  const totalQuantity = order.items.reduce((acc, it) => acc + it.quantity, 0);
  const formattedTime = new Date(order.createdAt).toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
  const formattedDate = new Date(order.createdAt).toLocaleDateString([], {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/75 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="relative w-full max-w-md max-h-[92vh] flex flex-col rounded-3xl bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 shadow-2xl overflow-hidden">
        {/* Top Notification / Action Bar */}
        <div className="px-5 py-3.5 bg-amber-600 text-white flex items-center justify-between no-print">
          <div className="flex items-center gap-2">
            {isAutoGenerated ? (
              <span className="w-8 h-8 rounded-full bg-white/25 flex items-center justify-center animate-bounce">
                <Bell className="w-4 h-4 fill-white text-white" />
              </span>
            ) : (
              <Printer className="w-5 h-5 text-white" />
            )}
            <div>
              <h3 className="text-sm font-bold leading-tight">
                {isAutoGenerated ? '🔔 New Order! Auto KOT Generated' : 'Kitchen Order Ticket (KOT)'}
              </h3>
              <p className="text-[11px] text-amber-100">
                {isAutoGenerated ? 'Ready for immediate kitchen dispatch' : `Order #${order.id}`}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-white text-amber-900 hover:bg-amber-50 font-bold text-xs rounded-xl shadow-xs flex items-center gap-1.5 cursor-pointer active:scale-95 transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print KOT</span>
            </button>
            {onClose && (
              <button
                onClick={onClose}
                className="p-1.5 rounded-full hover:bg-white/20 text-white cursor-pointer transition-colors"
                title="Close"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        {/* Scrollable Receipt Preview */}
        <div className="p-4 sm:p-6 overflow-y-auto flex justify-center bg-stone-100 dark:bg-stone-950/60">
          {/* Thermal Slip Card */}
          <div
            id="kot-print-area"
            className="w-full max-w-[340px] bg-white text-stone-950 p-5 rounded-xl border border-stone-300 shadow-sm font-mono text-xs leading-relaxed space-y-3"
          >
            {/* Header */}
            <div className="text-center pb-2 border-b-2 border-dashed border-stone-800 space-y-0.5">
              <p className="text-[11px] tracking-widest font-bold text-stone-500 uppercase">
                *** KITCHEN ORDER TICKET (KOT) ***
              </p>
              <h4 className="text-sm font-extrabold tracking-tight uppercase">
                {cafeInfo?.name || 'OUT OF THE TOWN (OTT)'}
              </h4>
              <p className="text-[10px] text-stone-600">
                Kukas, NH-48 Jaipur • Ph: +91 98289 19626
              </p>
            </div>

            {/* Order Meta Info */}
            <div className="py-1 border-b border-dashed border-stone-400 space-y-1 text-[11px]">
              <div className="flex justify-between font-bold">
                <span>ORDER: #{order.id}</span>
                <span className="bg-stone-900 text-white px-1.5 py-0.2 rounded-xs uppercase">
                  {order.orderType}
                </span>
              </div>
              <div className="flex justify-between text-stone-700">
                <span>DATE: {formattedDate}</span>
                <span>TIME: {formattedTime}</span>
              </div>
              {order.tableNumber && (
                <div className="text-xs font-black text-amber-900 bg-amber-100 px-1 py-0.5 rounded-xs border border-amber-300">
                  TABLE NO: {order.tableNumber.toUpperCase()}
                </div>
              )}
              <div className="flex justify-between text-stone-700">
                <span>CUSTOMER: {order.customerName}</span>
                <span>{order.customerPhone}</span>
              </div>
              {order.acceptedBy && (
                <div className="text-[10px] text-stone-600">
                  CHEF/STAFF: {order.acceptedBy}
                </div>
              )}
            </div>

            {/* Items Table */}
            <div className="space-y-1.5 py-1">
              <div className="flex justify-between font-bold text-[11px] pb-1 border-b border-stone-800">
                <span className="w-12">QTY</span>
                <span className="flex-1">ITEM DESCRIPTION</span>
                <span className="w-14 text-right">TYPE</span>
              </div>

              {order.items.map((it, idx) => (
                <div
                  key={idx}
                  className="flex justify-between items-start text-xs py-1 border-b border-stone-200"
                >
                  <span className="w-12 font-extrabold text-sm">{it.quantity} x</span>
                  <div className="flex-1 pr-1">
                    <span className="font-bold uppercase tracking-tight block">
                      {it.name}
                    </span>
                  </div>
                  <span
                    className={`w-14 text-right text-[10px] font-bold ${
                      it.isVeg ? 'text-emerald-700' : 'text-rose-700'
                    }`}
                  >
                    {it.isVeg ? '[VEG]' : '[NON-VEG]'}
                  </span>
                </div>
              ))}
            </div>

            {/* Total Items & Notes */}
            <div className="pt-1 border-t-2 border-dashed border-stone-800 space-y-1.5 text-[11px]">
              <div className="flex justify-between font-bold">
                <span>TOTAL ITEMS:</span>
                <span>{totalQuantity} QTY</span>
              </div>
              <div className="flex justify-between text-stone-700">
                <span>PREP TARGET:</span>
                <span>{order.estimatedTimeMinutes || 20} MINUTES</span>
              </div>

              {order.deliveryAddress && (
                <div className="pt-1 text-[10px] text-stone-800 border-t border-dotted border-stone-400">
                  <span className="font-bold">DELIVERY ADDRESS:</span> {order.deliveryAddress}
                </div>
              )}

              {order.statusNotes && (
                <div className="pt-1 text-[10px] italic text-stone-600">
                  Note: {order.statusNotes}
                </div>
              )}
            </div>

            {/* Footer Slip Tear Line */}
            <div className="text-center pt-2 border-t border-dashed border-stone-400 text-[10px] text-stone-500">
              <p>--- KITCHEN DISPATCH COPY ---</p>
              <p>Generated automatically via OTT POS System</p>
            </div>
          </div>
        </div>

        {/* Modal Bottom Actions */}
        <div className="p-4 bg-white dark:bg-stone-900 border-t border-stone-200 dark:border-stone-800 flex items-center justify-between no-print">
          <div className="flex items-center gap-1.5 text-xs text-stone-500 dark:text-stone-400">
            <Clock className="w-3.5 h-3.5 text-amber-600" />
            <span>Target: {order.estimatedTimeMinutes || 20} min</span>
          </div>

          <div className="flex items-center gap-2">
            {onClose && (
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-stone-600 hover:text-stone-900 dark:text-stone-300 dark:hover:text-white hover:bg-stone-100 dark:hover:bg-stone-800 cursor-pointer"
              >
                Close
              </button>
            )}
            <button
              type="button"
              onClick={handlePrint}
              className="px-5 py-2 rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs shadow-md flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>Print Kitchen KOT</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
