import type { MenuItem, Category, Order, Reservation, PromoBanner, CafeInfo } from '../src/types.js';

export class CafeStore {
  private static instance: CafeStore;

  public cafeInfo: CafeInfo = {
    name: 'Out of the Town - Restro and Bakery',
    tagline: 'Gourmet Restro, Artisan Bakery & Highway Retreat in Kukas, Jaipur',
    phone: '+91 98289 19626',
    email: 'care@outofthetownjaipur.com',
    address: 'SP 41 B, Near RIICO Industrial Area & Arya College of Industrial Training, Kukas, Delhi-Jaipur Highway (NH-48), Jaipur, Rajasthan 302038 (Near Umaid Haveli)',
    openingHours: 'Mon - Sun: 11:00 AM – 12:00 AM (Midnight)',
    announcement: '🌟 Welcome to Out of the Town - Restro and Bakery! Pure taste, fresh bakes & highway dining. Call Customer Care: +91 98289 19626',
  };

  public categories: Category[] = [
    {
      id: 'cat-all',
      name: 'All Dishes',
      slug: 'all',
      icon: 'Sparkles',
      description: 'Explore our full highway restro & bakery menu',
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-thali',
      name: 'Special Thalis',
      slug: 'thali',
      icon: 'UtensilsCrossed',
      description: 'Authentic royal Rajasthani & North Indian thalis',
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-bakery',
      name: 'Bakery & Cakes',
      slug: 'bakery',
      icon: 'Cake',
      description: 'Freshly baked cheesecakes, walnut brownies, pancakes & treats',
      image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-bites',
      name: 'Bites & Chaat',
      slug: 'bites',
      icon: 'Flame',
      description: 'Kurkure momos, spring rolls, paneer tikka & cheesy fries',
      image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-burgers',
      name: 'Burgers & Wraps',
      slug: 'burgers',
      icon: 'Sandwich',
      description: 'Gourmet loaded burgers, falafel wraps & triple-decker toasties',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-italian',
      name: 'Pizzas & Pastas',
      slug: 'italian',
      icon: 'Pizza',
      description: 'Stone-baked thin crust pizzas & creamy Alfredo pastas',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-mains',
      name: 'North Indian',
      slug: 'mains',
      icon: 'Soup',
      description: 'Rich paneer lababdar, dal makhani, laal maas & tandoori breads',
      image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-shakes',
      name: 'Shakes & Coolers',
      slug: 'shakes',
      icon: 'GlassWater',
      description: 'Thick Nutella & blueberry shakes, mojitos & Punjabi lassi',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'cat-coffee',
      name: 'Coffee & Chai',
      slug: 'coffee',
      icon: 'Coffee',
      description: 'Tiramisu cold coffee, iced frappes & earthen kulhad chai',
      image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=300&q=80',
    },
  ];

  public promoBanners: PromoBanner[] = [
    {
      id: 'promo-1',
      title: 'Royal Highway Feast: OTT Special Thali Combo',
      subtitle: 'Double Tadka Dal, Paneer Lababdar, Malai Kofta, Garlic Naan & Gulab Jamun at flat ₹100 OFF',
      highlightBadge: 'HIGHWAY SPECIAL',
      discountText: 'FLAT ₹100 OFF',
      code: 'OTTTHALI',
      imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
      badgeBgColor: 'bg-amber-600',
      targetCategory: 'thali',
      active: true,
      comboItemIds: ['item-1', 'item-15', 'item-14'],
      comboDescription: 'The royal banquet feast. Includes our premier OTT Special Royal Thali, accompanied by crisp Butter Garlic Naan (2 pcs) and slow-simmered Bukhara Dal Makhani.',
      terms: [
        'Flat ₹100 instant discount with promo code OTTTHALI',
        'Valid on dine-in, takeaway, and delivery',
        'Free highway doorstep delivery for orders above ₹499',
        'Freshly prepared in traditional tandoor and clay ovens',
      ],
    },
    {
      id: 'promo-2',
      title: 'Artisan Bakery Treat: Fresh Cheesecakes & Brownies',
      subtitle: 'Indulge in New York Blueberry Cheesecake & Sizzling Walnut Brownie with Hot Fudge',
      highlightBadge: 'FRESHLY BAKED',
      discountText: '25% OFF',
      code: 'BAKERY25',
      imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1200&q=80',
      badgeBgColor: 'bg-rose-600',
      targetCategory: 'bakery',
      active: true,
      comboItemIds: ['item-5', 'item-6', 'item-7'],
      comboDescription: 'Artisan dessert lovers combo: Savor a chilled slice of New York Blueberry Cheesecake, warm Sizzling Walnut Brownie with Belgian chocolate, and a Golden Pancake Stack.',
      terms: [
        'Flat 25% instant discount with promo code BAKERY25',
        'Baked fresh daily in-house by our master pastry chefs',
        'Packed in insulated eco-friendly pastry boxes',
        'Complimentary Belgian chocolate fudge drizzle',
      ],
    },
    {
      id: 'promo-3',
      title: 'Arya College & Highway Quick-Bite Combo',
      subtitle: 'Crispy Kurkure Momos + Peri-Peri Cheesy Fries + Chilled Thick Cold Coffee Frappe',
      highlightBadge: 'STUDENT & TRAVELER DEAL',
      discountText: '30% OFF',
      code: 'CAMPUS30',
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80',
      badgeBgColor: 'bg-indigo-600',
      targetCategory: 'bites',
      active: true,
      comboItemIds: ['item-8', 'item-9', 'item-18'],
      comboDescription: 'Our #1 trending highway snack combo: Crunchy fried kurkure momos served with fiery dip, loaded melted-cheese peri-peri fries, and thick Tiramisu cold coffee frappe.',
      terms: [
        'Flat 30% instant discount with promo code CAMPUS30',
        'Fast 15-minute preparation for quick highway pit-stops',
        'Special offer popular among college campus students',
        'Available all day and late night till 12:00 AM',
      ],
    },
    {
      id: 'promo-4',
      title: 'Lush Garden Lawn & Rooftop Dining Feast',
      subtitle: 'OTT Farmhouse Pizza + Creamy Alfredo White Penne + Thick Nutella Hazelnut Freakshake',
      highlightBadge: 'PARTY COMBO',
      discountText: 'FLAT ₹50 OFF',
      code: 'WELCOME50',
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
      badgeBgColor: 'bg-emerald-600',
      targetCategory: 'italian',
      active: true,
      comboItemIds: ['item-12', 'item-13', 'item-16'],
      comboDescription: 'The ultimate garden lawn party feast: 10-inch stone-baked Farmhouse Pizza loaded with mozzarella, Creamy Alfredo White Penne Pasta with garlic toast, and Nutella Freakshake.',
      terms: [
        'Flat ₹50 instant discount with promo code WELCOME50',
        'Ideal for sharing among 2-3 foodies or family dinners',
        'Free table reservation option in Garden Lawn or AC Lounge',
        'Fresh mozzarella and stone-oven fired crust',
      ],
    },
  ];

  public menuItems: MenuItem[] = [
    // 1. Thalis & Traditional Combos
    {
      id: 'item-1',
      name: 'OTT Special Royal Thali',
      category: 'thali',
      description: 'Double Tadka Dal, Paneer Lababdar, Malai Kofta, Rajasthani Sabzi, Garlic Naan, Stuffed Naan, Lachha Paratha, Jeera Pulao, Gulab Jamun, Salad & Roasted Papad.',
      price: 499,
      originalPrice: 550,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 420,
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80',
      tags: ['Chef Signature', 'Grand Feast', 'Rajasthani'],
      preparationTimeMinutes: 20,
    },
    {
      id: 'item-2',
      name: 'Out of Town Special Thali',
      category: 'thali',
      description: 'Double Tadka Dal, Seasonal Green Vegetable, Paneer Lababdar, Butter/Garlic Naan, Lachha Paratha, Jeera Rice, Boondi Raita, Gulab Jamun & Papad.',
      price: 330,
      originalPrice: 360,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 310,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      tags: ['Bestseller Thali', 'Vegetarian'],
      preparationTimeMinutes: 18,
    },
    {
      id: 'item-3',
      name: 'Executive Highway Lunch Thali',
      category: 'thali',
      description: 'Authentic Yellow Dal Tadka, Seasonal Mixed Vegetable Sabzi, 2 pcs Tandoori Roti, Steamed Basmati Rice & Fresh Sliced Salad.',
      price: 230,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 195,
      image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80',
      tags: ['Quick Lunch', 'Pocket Friendly'],
      preparationTimeMinutes: 15,
    },
    {
      id: 'item-4',
      name: 'Rajasthani Laal Maas Curry Platter',
      category: 'thali',
      description: 'Authentic slow-simmered tender meat curry infused with fragrant Mathania red chilies, served with missi rotis and aromatic jeera rice.',
      price: 450,
      originalPrice: 490,
      isVeg: false,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 380,
      image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80',
      tags: ['Royal Rajasthani', 'Spicy', 'Non-Veg'],
      preparationTimeMinutes: 22,
    },

    // 2. Artisan Bakery & Patisserie
    {
      id: 'item-5',
      name: 'Blueberry New York Cheesecake',
      category: 'bakery',
      description: 'Velvety cream cheese cake baked to golden perfection, topped with house-made wild blueberry compote and buttery graham crust.',
      price: 210,
      originalPrice: 240,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 510,
      image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
      tags: ['Artisan Bakery', 'Signature', 'Eggless'],
      preparationTimeMinutes: 5,
    },
    {
      id: 'item-6',
      name: 'Sizzling Walnut Brownie with Ice Cream',
      category: 'bakery',
      description: 'Gooey warm dark chocolate walnut brownie served on a cast iron sizzler with rich vanilla bean ice cream and hot chocolate fudge.',
      price: 200,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 480,
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
      tags: ['Sizzler Special', 'Chocolate Lovers'],
      preparationTimeMinutes: 8,
    },
    {
      id: 'item-7',
      name: 'Nutella Hazelnut Fluffy Pancakes',
      category: 'bakery',
      description: 'Stack of three golden buttermilk pancakes drenched with warm Nutella spread, roasted crunchy hazelnuts and whipped cream.',
      price: 240,
      originalPrice: 270,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 230,
      image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
      tags: ['All-Day Breakfast', 'Nutella'],
      preparationTimeMinutes: 12,
    },
    {
      id: 'item-8',
      name: 'Red Velvet Gateau Cake',
      category: 'bakery',
      description: 'Moist crimson cocoa sponge layered with delicate whipped cream cheese frosting and white chocolate curls.',
      price: 190,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 180,
      image: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=600&q=80',
      tags: ['Bakery Counter', 'Pastry'],
      preparationTimeMinutes: 5,
    },
    {
      id: 'item-9',
      name: 'Hot Gulab Jamun in Saffron Syrup (2 Pcs)',
      category: 'bakery',
      description: 'Soft melt-in-the-mouth khoya dumplings soaked in warm green cardamom and Kashmiri saffron sugar syrup.',
      price: 50,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 340,
      image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
      tags: ['Traditional Sweet', 'Hot Dessert'],
      preparationTimeMinutes: 3,
    },

    // 3. Bite Up & Chaat (Appetizers)
    {
      id: 'item-10',
      name: 'Achari Paneer Tikka (Tandoori)',
      category: 'bites',
      description: 'Fresh farm cottage cheese cubes marinated in piquant Rajasthani pickling spices and hung curd, roasted in clay tandoor with charred bell peppers.',
      price: 330,
      originalPrice: 360,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 290,
      image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
      tags: ['Tandoor Oven', 'Spicy', 'Gluten-Free'],
      preparationTimeMinutes: 16,
    },
    {
      id: 'item-11',
      name: 'Kurkure Crispy Fried Momos (8 Pcs)',
      category: 'bites',
      description: 'Golden crunchy cornflake-crusted steamed dumplings filled with spiced cabbage, carrot, and paneer. Served with fiery red chili chutney & mayonnaise.',
      price: 160,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 620,
      image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
      tags: ['Student Favorite', 'Crunchy', 'Fiery Dip'],
      preparationTimeMinutes: 12,
    },
    {
      id: 'item-12',
      name: 'OTT Special Buttery Pav Bhaji',
      category: 'bites',
      description: 'Highway-style spiced mashed seasonal vegetables slow-cooked on flat tava with generous Amul butter, served with soft butter-toasted pavs.',
      price: 180,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 410,
      image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80',
      tags: ['Street Food', 'Amul Butter', 'Popular'],
      preparationTimeMinutes: 14,
    },
    {
      id: 'item-13',
      name: 'Hare Bhare Kebab (6 Pcs)',
      category: 'bites',
      description: 'Shallow pan-crisped kebabs made with fresh spinach, green peas, mashed potatoes and cottage cheese, scented with roasted cumin.',
      price: 240,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 165,
      image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
      tags: ['Healthy Snack', 'Spinach & Peas'],
      preparationTimeMinutes: 14,
    },
    {
      id: 'item-14',
      name: 'Loaded Cheese Peri-Peri Fries',
      category: 'bites',
      description: 'Crisp golden potato fries tossed in tangy peri-peri spice blend and smothered with warm molten cheese sauce.',
      price: 150,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 380,
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      tags: ['Cheesy', 'Quick Bites'],
      preparationTimeMinutes: 10,
    },
    {
      id: 'item-15',
      name: 'Highway Butter Tadka Maggi',
      category: 'bites',
      description: 'Classic 2-minute noodles elevated with sauteed diced onions, tomatoes, sweet corn, melted butter and house spice sprinkle.',
      price: 100,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 210,
      image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
      tags: ['Comfort Food', 'Late Night'],
      preparationTimeMinutes: 8,
    },

    // 4. Burgers, Wraps & Sandwiches
    {
      id: 'item-16',
      name: 'Crispy BBQ Paneer Burger',
      category: 'burgers',
      description: 'Crispy panko-breaded spiced paneer steak topped with smoked barbecue sauce, pickled jalapeños, cheddar cheese and caramelized onions.',
      price: 200,
      originalPrice: 220,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 310,
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      tags: ['Chef Special', 'Gourmet Burger'],
      preparationTimeMinutes: 14,
    },
    {
      id: 'item-17',
      name: 'Aloo Tikki Sriracha Burger',
      category: 'burgers',
      description: 'Golden spiced herb potato patty with fiery sriracha mayo, crisp iceberg lettuce, sliced tomatoes and gherkins in a toasted sesame bun.',
      price: 150,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 240,
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
      tags: ['Spicy Aioli', 'Crunchy'],
      preparationTimeMinutes: 12,
    },
    {
      id: 'item-18',
      name: 'Gourmet Chicken Tikka Sandwich',
      category: 'burgers',
      description: 'Charred tandoori chicken tikka strips tossed in mint mayo and cheddar, pressed between thick slices of grilled artisan bread.',
      price: 220,
      isVeg: false,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 280,
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
      tags: ['Non-Veg', 'High Protein', 'Grilled'],
      preparationTimeMinutes: 15,
    },
    {
      id: 'item-19',
      name: 'Falafel & Creamy Hummus Wrap',
      category: 'burgers',
      description: 'Golden spiced chickpea falafels with velvety garlic hummus, pickled cucumbers, shredded purple cabbage and tahini dressing in flatbread.',
      price: 220,
      isVeg: true,
      isVegan: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 175,
      image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80',
      tags: ['Mediterranean', 'Vegan'],
      preparationTimeMinutes: 12,
    },
    {
      id: 'item-20',
      name: 'Roasted Veg Fajita Wrap',
      category: 'burgers',
      description: 'Char-grilled bell peppers, zucchini, caramelized red onions and spiced chipotle salsa wrapped in a warm tortilla with melted cheese.',
      price: 150,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.6,
      reviewsCount: 130,
      image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
      tags: ['Mexican Spiced', 'Light Meal'],
      preparationTimeMinutes: 12,
    },
    {
      id: 'item-21',
      name: 'Bombay Grilled Cheese Sandwich',
      category: 'burgers',
      description: 'Three layers of buttered bread filled with spicy boiled potato masala, sliced cucumbers, tomatoes, spicy coriander chutney and gooey cheese.',
      price: 160,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 320,
      image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=600&q=80',
      tags: ['Classic Toastie', 'Cheesy'],
      preparationTimeMinutes: 12,
    },

    // 5. Pizzas & Pastas
    {
      id: 'item-22',
      name: 'OTT Farmhouse Special Pizza (10")',
      category: 'italian',
      description: 'Hand-stretched thin crust stone-baked pizza loaded with paneer cubes, crisp bell peppers, black olives, sweet corn and 100% mozzarella.',
      price: 280,
      originalPrice: 320,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 390,
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      tags: ['Wood-Fired Style', 'Stone Oven'],
      preparationTimeMinutes: 18,
    },
    {
      id: 'item-23',
      name: 'Creamy Alfredo White Sauce Penne Pasta',
      category: 'italian',
      description: 'Durum wheat penne tossed in cultured garlic cream cheese sauce, sauteed broccoli, bell peppers, fresh basil and grated parmesan.',
      price: 230,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 310,
      image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=600&q=80',
      tags: ['Rich Alfredo', 'Cheesy'],
      preparationTimeMinutes: 15,
    },
    {
      id: 'item-24',
      name: 'Spicy Peri-Peri Arrabbiata Pasta',
      category: 'italian',
      description: 'Penne pasta simmered in a robust slow-cooked San Marzano tomato sauce spiked with peri-peri chili flakes, black olives, and herbs.',
      price: 220,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 215,
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      tags: ['Tangy & Fiery', 'Italian Herbs'],
      preparationTimeMinutes: 14,
    },

    // 6. North Indian Mains & Breads
    {
      id: 'item-25',
      name: 'Paneer Butter Masala (Rich Gravy)',
      category: 'mains',
      description: 'Succulent malai cottage cheese cubes gently cooked in a velvety tomato-cashew satin gravy with fresh dairy cream and dried fenugreek.',
      price: 290,
      originalPrice: 320,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 450,
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
      tags: ['Mughlai & North Indian', 'Royal Dish'],
      preparationTimeMinutes: 16,
    },
    {
      id: 'item-26',
      name: 'Double Tadka Dal Makhani',
      category: 'mains',
      description: 'Black urad lentils and kidney beans slow-simmered for 14 hours over low embers, enriched with cultured butter and finished with garlic tadka.',
      price: 240,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 410,
      image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?auto=format&fit=crop&w=600&q=80',
      tags: ['Slow Cooked', 'Authentic Tadka'],
      preparationTimeMinutes: 14,
    },
    {
      id: 'item-27',
      name: 'Butter Garlic Naan (2 Pcs)',
      category: 'mains',
      description: 'Tandoor-baked leavened refined flour flatbread generously smeared with roasted minced garlic, fresh coriander and dairy butter.',
      price: 90,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 520,
      image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
      tags: ['Clay Oven', 'Fresh Tandoor'],
      preparationTimeMinutes: 8,
    },

    // 7. Thick Shakes & Coolers
    {
      id: 'item-28',
      name: 'Nutella Hazelnut Loaded Thick Shake',
      category: 'shakes',
      description: 'Decadent shake blended with genuine Italian Nutella, rich dairy ice cream, crushed Ferrero crumble and chocolate syrup drizzle.',
      price: 210,
      originalPrice: 240,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 480,
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      tags: ['Signature Shake', 'Nutella Bliss'],
      preparationTimeMinutes: 6,
    },
    {
      id: 'item-29',
      name: 'Wild Blueberry Velvet Shake',
      category: 'shakes',
      description: 'Real blueberry puree whipped with thick ice cream and chilled whole milk, served with blueberry drizzle.',
      price: 180,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.8,
      reviewsCount: 320,
      image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=600&q=80',
      tags: ['Fruity & Creamy', 'Thick Shake'],
      preparationTimeMinutes: 5,
    },
    {
      id: 'item-30',
      name: 'Blue Lagoon Citrus Cooler',
      category: 'shakes',
      description: 'Refreshing sparkling curaçao cooler with muddled fresh mint leaves, lemon wedges, and crushed ice.',
      price: 150,
      isVeg: true,
      isVegan: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 210,
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      tags: ['Chilled Cooler', 'Summer Hit'],
      preparationTimeMinutes: 4,
    },
    {
      id: 'item-31',
      name: 'Traditional Sweet Punjabi Lassi',
      category: 'shakes',
      description: 'Authentic curd hand-churned with sugar, fragrant rose water and cardamom, topped with thick clotted malai in a mud cup.',
      price: 80,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 350,
      image: 'https://images.unsplash.com/photo-1571006682875-a82f3efc2250?auto=format&fit=crop&w=600&q=80',
      tags: ['Clay Pot', 'Malai Topped'],
      preparationTimeMinutes: 4,
    },

    // 8. Specialty Coffee & Kulhad Chai
    {
      id: 'item-32',
      name: 'Tiramisu Cold Coffee',
      category: 'coffee',
      description: 'Double espresso blended with chilled milk, vanilla bean ice cream and mascarpone tiramisu notes, crowned with dark cocoa powder.',
      price: 160,
      originalPrice: 190,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 430,
      image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80',
      tags: ['Signature Cold Brew', 'Best in Jaipur'],
      preparationTimeMinutes: 5,
    },
    {
      id: 'item-33',
      name: 'Kulhad Wali Winter Special Chai',
      category: 'coffee',
      description: 'Slow-simmered rich Indian highway tea brewed with fresh crushed ginger, green cardamom and cloves, served piping hot in an earthen kulhad.',
      price: 40,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 690,
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      tags: ['Earthen Kulhad', 'Highway Chai', 'Pure Joy'],
      preparationTimeMinutes: 6,
    },
    {
      id: 'item-34',
      name: 'OTT Signature Highway Masala Chai',
      category: 'coffee',
      description: 'Signature spiced road-trip tea made with CTC Assam leaves, whole milk, and our secret 7-spice house blend.',
      price: 50,
      isVeg: true,
      isBestseller: true,
      isAvailable: true,
      rating: 4.9,
      reviewsCount: 510,
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      tags: ['All-Time Favorite', 'Spiced Tea'],
      preparationTimeMinutes: 5,
    },
    {
      id: 'item-35',
      name: 'Classic Iced Cappuccino',
      category: 'coffee',
      description: 'Chilled bold espresso poured over ice and crowned with dense, velvety micro-foam and chocolate dust.',
      price: 100,
      isVeg: true,
      isBestseller: false,
      isAvailable: true,
      rating: 4.7,
      reviewsCount: 190,
      image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
      tags: ['Chilled Coffee', 'Espresso Bar'],
      preparationTimeMinutes: 4,
    },
  ];

  // Live real orders created by customers (zero fake / demo orders)
  public orders: Order[] = [];

  // Live real reservations made by customers
  public reservations: Reservation[] = [];

  public customers: {
    id: string;
    name: string;
    phone: string;
    email: string;
    createdAt: string;
    lastLogin?: string;
  }[] = [
    {
      id: 'CUST-1001',
      name: 'Satyam Kumar',
      phone: '9828919626',
      email: 'kumarsatyam5868@gmail.com',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      lastLogin: new Date().toISOString(),
    },
  ];

  public pendingOtps: Map<string, {
    otp: string;
    email: string;
    phone: string;
    name?: string;
    expiresAt: number;
  }> = new Map();

  public customerTokens: Map<string, {
    id: string;
    name: string;
    phone: string;
    email: string;
    createdAt: string;
    lastLogin?: string;
  }> = new Map();

  public static getInstance(): CafeStore {
    if (!CafeStore.instance) {
      CafeStore.instance = new CafeStore();
      // Seed default customer token for instant session persistence
      if (CafeStore.instance.customers.length > 0) {
        CafeStore.instance.customerTokens.set(
          'cust-mock-jwt-token-CUST-1001',
          CafeStore.instance.customers[0]
        );
      }
    }
    return CafeStore.instance;
  }
}

export const store = CafeStore.getInstance();
